stages:
- name: go-build
  steps:
  - runScriptConfig:
      image: golang:1.8
      shellScript: "mkdir -p /go/src/github.com/golang\nln -s $(pwd) /go/src/github.com/golang/example
        \ncd  /go/src/github.com/golang/example/outyet\nGODS=linux GOARCH=amd64 CGO_ENABLED=0
        go build -o bin/outyet\n      "
- name: go-test
  steps:
  - runScriptConfig:
      image: golang:1.8
      shellScript: "mkdir -p /go/src/github.com/golang\nln -s $(pwd) /go/src/github.com/golang/example
        \ncd  /go/src/github.com/golang/example/outyet\ngo test"
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./outyet/Dockerfile
      buildContext: .
      tag: example/app:v1
      pushRemote: true
      registry: quay.io
timeout: 60
